config/routes.rb
Rails.application.routes.draw do
  resources :landings, only: :show

  get '/:agreement', to: 'agreements#show', constraints: { subdomain: '', agreement: /(tos|privacy_policy)/ }

  match '/', to: 'landings#show', constraints: { subdomain: '' }, via: :get

  constraints AdminSubdomain do
    devise_for :admins,
      path: '/',
      path_names: {
        sign_up: 'new',
        sign_out: 'logout',
        password: 'secret',
        registration: 'profile'
      }

    root to: 'dashboards#show'

    as :admin do
      get '/profile/edit', to: 'devise/registrations#edit', as: 'edit_admin_registration'
      put '/profile', to: 'devise/registrations#update', as: 'admin_registration'
    end

    resource :dashboard, only: :show
    resource :stats, only: :show
    resource :settings, only: %w(edit update)

    resources :agreements
    resources :users, only: %w(index show)
    resources :devices, only: %w(index show)
    resources :routers
    resources :stats, only: :show do
      collection do
        get :social_networks
        get :gender
        get :activity
        get :events
      end
    end
    resources :companies do
      resources :admins, only: %w(new create)
      member do
        put :hold
        get :suspended
      end
    end
    resources :pages, only: :tos do
      collection do
        get :tos
        get :tos_edit
        put :tos_update
      end
    end
    namespace :social do
      resource :vk, only: %w(edit update)
      resource :fb, only: %w(edit update)
      resource :tw, only: %w(edit update)
      resource :in, only: %w(edit update)
      resource :ok, only: %w(edit update)
      resource :sms, only: %w(edit update)
      resource :guest, only: %w(edit update)
    end
    post '/events/by_date', to: 'events#by_date', as: 'events_by_date'
  end

  constraints OauthSubdomain do
    resource :widget, only: :show

    namespace :sms do
      get 'authorize', to: 'auth#index'
      post 'auth/send_sms'
      match 'auth/validate', via: %w(get post)
    end

    post '/password', to: 'visitors#auth_by_password'
    get '/:provider/subscribe', to: 'events#subscribe', as: 'event_subscribe'
    match '/:provider/post', to: 'events#post', as: 'event_post', via: [:get, :post]
    get '/:provider/auth', to: 'events#auth', as: 'event_auth'
    get '/:provider/is_member', to: 'events#is_member', as: 'event_member'
    get '/:provider/callback', to: 'sessions#create'
    get '/:provider/setup', to: 'sessions#setup'
    get '/failure', to: 'sessions#failure'
    get '/', to: 'visitors#index', as: :auth
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :save_params
  before_action :load_company
  before_action :load_router

  layout :visitors_layout

  def index
    return render_404 unless @company && @router
    redirect_to suspended_company_path(@company) and return unless @company.try(:active)

    if @company.sms.action.eql?('ident') || @company.sms.action.eql?('ident_auth')
      device = @company.devices.find_by_mac(session[:mac])
      return redirect_to sms_authorize_path unless device
      return unless @company.sms.action.eql?('ident') && @company.sms.adv
      render 'widgets/sms/adv'
    end
  end

  def auth_by_password
    if @company && @company.guest.password_digest && @company.guest.authenticate(params[:password])
      redirect_to event_auth_path(:guest_password)
    else
      flash[:alert] = t('.error')
      redirect_to auth_path
    end
  end

  private

  def visitors_layout
    return unless @company
    @company.layout.eql?('visitors_bg') ? 'visitors_bg' : 'visitors'
  end

  def save_params
    return unless params[:hs] && params[:hs][:mac_esc] && params[:hs][:router]

    session[:company_token] = params[:hs][:token]
    session[:router_token] = params[:hs][:router]
    session[:router_identity] = params[:hs][:identity]
    session[:link] = params[:hs][:link_login_only]
    session[:dst] = params[:hs][:dst]
    session[:mac] = mac_address(params[:hs][:mac_esc])
    session[:ip] = params[:hs][:ip_esc]
  end

  def load_company
    @company = Company.find_by_token(session[:company_token])
  end

  def load_router
    @router = Router.find_by_token(session[:router_token])
  end
end

app/views/visitors/404.html.haml
Not Found

app/views/visitors/_password.html.haml
.row
  .col-xs-6.col-xs-offset-3
    = form_tag password_path, method: :post do
      .input-group.input-group-lg
        = password_field_tag :password, nil, placeholder: t('.placeholder'), class: 'form-control'
        %span.input-group-btn
          = submit_tag 'Go', class: 'btn btn-lg btn-success'

app/views/visitors/_tos_modal.html.haml
.modal.fade#tos{tabindex: '-1', role: 'dialog'}
  .modal-dialog{role: 'document'}
    .modal-content
      .modal-header
        %button.close{'data-dismiss': 'modal', 'aria-label': 'Close'}
          %span{'aria-hidden': true} &times;
        %h4.modal-title#tosLable= t('pages.tos')
      .modal-body.tos-modal
        = markdown(@company.tos_text) if @company.tos_text.present?

app/views/visitors/index.html.haml
.text-center
  %h1= @company.name
  %p= t('.welcome')
  %ul.list-inline
    - unless @company.fb.action.eql?('disabled')
      %li
        = link_to '/facebook', class: 'social' do
          = image_tag 'facebook.png'
    - unless @company.tw.action.eql?('disabled')
      %li
        = link_to '/twitter', class: 'social' do
          = image_tag 'twitter.png'
    - unless @company.vk.action.eql?('disabled')
      %li
        = link_to '/vkontakte', class: 'social' do
          = image_tag 'vkontakte.png'
    - unless @company.in.action.eql?('disabled')
      %li
        = link_to '/instagram', class: 'social' do
          = image_tag 'instagram.png'
    - unless @company.ok.action.eql?('disabled')
      %li
        = link_to '/odnoklassniki', class: 'social' do
          = image_tag 'ok.png'
    - if @company.sms.action.eql?('auth') || @company.sms.action.eql?('ident_auth')
      %li
        = link_to '/sms/authorize', class: 'social' do
          = image_tag 'sms.png'

  - if @company.guest.action.eql?('skip')
    .list-inline= link_to t('.continue'), '/guest', class: 'btn btn-lg btn-success'

  - if @company.guest.action.eql?('auth')
    = render 'visitors/password'

  - if @company.tos?
    = render 'visitors/tos_modal'
    %label{ for: 'accept_tos' }
      = check_box_tag 'accept_tos', 'yes', false
      = t('visitors.index.tos')
      = link_to t('visitors.index.tos_link'), '#', data: { toggle:"modal", target: '#tos' }

  - if @company.card?
    %h3.text-center
      = link_to t('.download_card'), @company.card.url,
        download: @company.name.underscore.parameterize("_"),
        onclick: "location='#{router_url}'", class: 'btn btn-primary'

  - if @company.cover? && @company.layout? && @company.layout.eql?('visitors')
    = image_tag @company.cover.url, alt: @company.name, class: 'img-responsive'

:javascript
  initializeTos(#{@company.tos?});