config/routes.rb
Rails.application.routes.draw do
  resources :landings, only: :show

  get '/:agreement', to: 'agreements#show', constraints: { subdomain: '', agreement: /(tos|privacy_policy)/ }

  match '/', to: 'landings#show', constraints: { subdomain: '' }, via: :get

  constraints AdminSubdomain do
    devise_for :admins,
      path: '/',
      path_names: {
        sign_up: 'new',
        sign_out: 'logout',
        password: 'secret',
        registration: 'profile'
      }

    root to: 'dashboards#show'

    as :admin do
      get '/profile/edit', to: 'devise/registrations#edit', as: 'edit_admin_registration'
      put '/profile', to: 'devise/registrations#update', as: 'admin_registration'
    end

    resource :dashboard, only: :show
    resource :stats, only: :show
    resource :settings, only: %w(edit update)

    resources :agreements
    resources :users, only: %w(index show)
    resources :devices, only: %w(index show)
    resources :routers
    resources :stats, only: :show do
      collection do
        get :social_networks
        get :gender
        get :activity
        get :events
      end
    end
    resources :companies do
      resources :admins, only: %w(new create)
      member do
        put :hold
        get :suspended
      end
    end
    resources :pages, only: :tos do
      collection do
        get :tos
        get :tos_edit
        put :tos_update
      end
    end
    namespace :social do
      resource :vk, only: %w(edit update)
      resource :fb, only: %w(edit update)
      resource :tw, only: %w(edit update)
      resource :in, only: %w(edit update)
      resource :ok, only: %w(edit update)
      resource :sms, only: %w(edit update)
      resource :guest, only: %w(edit update)
    end
    post '/events/by_date', to: 'events#by_date', as: 'events_by_date'
  end

  constraints OauthSubdomain do
    resource :widget, only: :show

    namespace :sms do
      get 'authorize', to: 'auth#index'
      post 'auth/send_sms'
      match 'auth/validate', via: %w(get post)
    end

    post '/password', to: 'visitors#auth_by_password'
    get '/:provider/subscribe', to: 'events#subscribe', as: 'event_subscribe'
    match '/:provider/post', to: 'events#post', as: 'event_post', via: [:get, :post]
    get '/:provider/auth', to: 'events#auth', as: 'event_auth'
    get '/:provider/is_member', to: 'events#is_member', as: 'event_member'
    get '/:provider/callback', to: 'sessions#create'
    get '/:provider/setup', to: 'sessions#setup'
    get '/failure', to: 'sessions#failure'
    get '/', to: 'visitors#index', as: :auth
  end
end

app/views/shared/_error_message.html.haml
- if object.errors.any?
  #error_explanation
    %h2= t('.form_contains', count: pluralize(object.errors.count, 'error'))
    %ul
      - object.errors.full_messages.each do |error|
        %li= error

app/views/shared/_settings_links.html.haml
%h2= t('settings.edit.settings')
%ul.nav.nav-tabs.nav-justified.settings-links
  %li{ class: controller?('settings') && action?('edit') ? 'active' : '' }
    = link_to edit_settings_path do
      %i.fa.fa-lg.fa-home
      = t('.start_page')
  %li{ class: controller?('social/fbs') ? 'active' : '' }
    = link_to edit_social_fb_path do
      %i.fa.fa-lg.fa-facebook-square
      = t('.facebook')
  %li{ class: controller?('social/vks') ? 'active' : '' }
    = link_to edit_social_vk_path do
      %i.fa.fa-lg.fa-vk
      = t('.vkontakte')
  %li{ class: controller?('social/tws') ? 'active' : '' }
    = link_to edit_social_tw_path do
      %i.fa.fa-lg.fa-twitter-square
      = t('.twitter')
  %li{ class: controller?('social/ins') ? 'active' : '' }
    = link_to edit_social_in_path do
      %i.fa.fa-lg.fa-instagram
      = t('.instagram')
  %li{ class: controller?('social/oks') ? 'active' : '' }
    = link_to edit_social_ok_path do
      %i.fa.fa-lg.fa-odnoklassniki-square
      = t('.odnoklassniki')
  %li{ class: controller?('social/sms') ? 'active' : '' }
    = link_to edit_social_sms_path do
      %i.fa.fa-lg.fa-comments
      = t('.sms')
  %li{ class: controller?('social/guests') ? 'active' : '' }
    = link_to edit_social_guest_path do
      %i.fa.fa-lg.fa-unlock
      = t('.guest')
  %li{ class: controller?('pages') && (action?('tos') || action?('tos_edit')) ? 'active' : '' }
    = link_to tos_pages_path do
      %i.fa.fa-lg.fa-check-square
      = t('.tos')