config/routes.rb
Rails.application.routes.draw do
  resources :landings, only: :show

  get '/:agreement', to: 'agreements#show', constraints: { subdomain: '', agreement: /(tos|privacy_policy)/ }

  match '/', to: 'landings#show', constraints: { subdomain: '' }, via: :get

  constraints AdminSubdomain do
    devise_for :admins,
      path: '/',
      path_names: {
        sign_up: 'new',
        sign_out: 'logout',
        password: 'secret',
        registration: 'profile'
      }

    root to: 'dashboards#show'

    as :admin do
      get '/profile/edit', to: 'devise/registrations#edit', as: 'edit_admin_registration'
      put '/profile', to: 'devise/registrations#update', as: 'admin_registration'
    end

    resource :dashboard, only: :show
    resource :stats, only: :show
    resource :settings, only: %w(edit update)

    resources :agreements
    resources :users, only: %w(index show)
    resources :devices, only: %w(index show)
    resources :routers
    resources :stats, only: :show do
      collection do
        get :social_networks
        get :gender
        get :activity
        get :events
      end
    end
    resources :companies do
      resources :admins, only: %w(new create)
      member do
        put :hold
        get :suspended
      end
    end
    resources :pages, only: :tos do
      collection do
        get :tos
        get :tos_edit
        put :tos_update
      end
    end
    namespace :social do
      resource :vk, only: %w(edit update)
      resource :fb, only: %w(edit update)
      resource :tw, only: %w(edit update)
      resource :in, only: %w(edit update)
      resource :ok, only: %w(edit update)
      resource :sms, only: %w(edit update)
      resource :guest, only: %w(edit update)
    end
    post '/events/by_date', to: 'events#by_date', as: 'events_by_date'
  end

  constraints OauthSubdomain do
    resource :widget, only: :show

    namespace :sms do
      get 'authorize', to: 'auth#index'
      post 'auth/send_sms'
      match 'auth/validate', via: %w(get post)
    end

    post '/password', to: 'visitors#auth_by_password'
    get '/:provider/subscribe', to: 'events#subscribe', as: 'event_subscribe'
    match '/:provider/post', to: 'events#post', as: 'event_post', via: [:get, :post]
    get '/:provider/auth', to: 'events#auth', as: 'event_auth'
    get '/:provider/is_member', to: 'events#is_member', as: 'event_member'
    get '/:provider/callback', to: 'sessions#create'
    get '/:provider/setup', to: 'sessions#setup'
    get '/failure', to: 'sessions#failure'
    get '/', to: 'visitors#index', as: :auth
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  load_and_authorize_resource :company, through: :current_admin, singleton: true

  def edit
  end

  def update
    if @company.update(company_params)
      @company.fb.update(fb_params)
      @company.vk.update(vk_params)
      @company.tw.update(tw_params)
      @company.in.update(in_params)
      @company.ok.update(ok_params)
      @company.sms.update(sms_params)
      @company.guest.update(guest_params)
      redirect_to edit_settings_path, notice: t('.success')
    else
      render :edit
    end
  end

  private

  def fb_params
    params.require(:fb).permit(:action)
  end

  def vk_params
    params.require(:vk).permit(:action)
  end

  def tw_params
    params.require(:tw).permit(:action)
  end

  def in_params
    params.require(:in).permit(:action)
  end

  def ok_params
    params.require(:ok).permit(:action)
  end

  def sms_params
    params.require(:sms).permit(:action)
  end

  def guest_params
    params.require(:guest).permit(:action)
  end

  def company_params
    params.require(:company).permit(
      :link_redirect,
      :action,
      :cover,
      :cover_cache,
      :remove_cover,
      :card,
      :card_cache,
      :remove_card,
      :tos,
      :tos_text,
      :layout
    )
  end
end

app/views/settings/edit.html.haml
= render 'shared/settings_links'

= form_for @company, url: settings_path, method: :put do |f|
  .col-md-8.col-md-offset-2
    .row
      .col-md-6
        = fields_for @company.fb do |fb|
          .form-group
            = fb.label :facebook
            = fb.select :action, [[t('.like_page'), :join], [t('.make_post'), :post], [t('.just_auth'), :auth], [t('.disabled'), :disabled]], {}, class: 'form-control'
        = fields_for @company.vk do |vk|
          .form-group
            = vk.label :vkontakte, t('.vkontakte')
            = vk.select :action, [[t('.join_group'), :join], [t('.upload_photo'), :post], [t('.just_auth'), :auth], [t('.disabled'), :disabled]], {}, class: 'form-control'
        = fields_for @company.tw do |tw|
          .form-group
            = tw.label :twitter
            = tw.select :action,[[t('.follow'), :join], [t('.make_tweet'), :post], [t('.just_auth'), :auth], [t('.disabled'), :disabled]], {}, class: 'form-control'
        = fields_for @company.in do |ins|
          .form-group
            = ins.label :instagram
            = ins.select :action, [[t('.just_auth'), :auth], [t('.disabled'), :disabled]], {}, class: 'form-control'
      .col-md-6
        = fields_for @company.ok do |ok|
          .form-group
            = ok.label :odnoklassniki, t('.odnoklassniki')
            = ok.select :action, [[t('.join_group'), :join], [t('.just_auth'), :auth], [t('.disabled'), :disabled]], {}, class: 'form-control'
        = fields_for @company.sms do |sms|
          .form-group
            = sms.label :sms, t('.sms')
            = sms.select :action, [[t('.disabled'), :disabled], [t('.just_auth'), :auth], [t('.sms_ident'), :ident], [t('.sms_ident_auth'), :ident_auth]], {}, class: 'form-control'
        = fields_for @company.guest do |guest|
          .form-group
            = guest.label :action, t('.auth')
            = guest.select :action, [[t('.disabled'), :disabled], [t('.password'), :auth], [t('.skip'), :skip]], {}, class: 'form-control'
        .form-group
          = f.label :layout, t('.layout')
          = f.select :layout, [[t('.visitors'), :visitors], [t('.visitors_bg'), :visitors_bg]], {}, class: 'form-control'
    .row
      .col-md-6
        .form-group
          = f.label :cover, t('.cover')
          - if @company.cover?
            %div
            = image_tag(@company.cover)
          = f.file_field :cover
          %p.help-block
            = @company.cover.extension_white_list.join(', ')
          = f.hidden_field :cover_cache
        .checkbox
          %label
            = f.check_box :remove_cover
            = f.label :remove_cover, t('.remove_cover')
      .col-md-6
        .checkbox
          %label
            = f.check_box :tos
            = f.label :tos, t('.tos')
        .form-group
          = f.submit t('.save'), class: 'btn btn-primary'