config/routes.rb
Rails.application.routes.draw do
  resources :landings, only: :show

  get '/:agreement', to: 'agreements#show', constraints: { subdomain: '', agreement: /(tos|privacy_policy)/ }

  match '/', to: 'landings#show', constraints: { subdomain: '' }, via: :get

  constraints AdminSubdomain do
    devise_for :admins,
      path: '/',
      path_names: {
        sign_up: 'new',
        sign_out: 'logout',
        password: 'secret',
        registration: 'profile'
      }

    root to: 'dashboards#show'

    as :admin do
      get '/profile/edit', to: 'devise/registrations#edit', as: 'edit_admin_registration'
      put '/profile', to: 'devise/registrations#update', as: 'admin_registration'
    end

    resource :dashboard, only: :show
    resource :stats, only: :show
    resource :settings, only: %w(edit update)

    resources :agreements
    resources :users, only: %w(index show)
    resources :devices, only: %w(index show)
    resources :routers
    resources :stats, only: :show do
      collection do
        get :social_networks
        get :gender
        get :activity
        get :events
      end
    end
    resources :companies do
      resources :admins, only: %w(new create)
      member do
        put :hold
        get :suspended
      end
    end
    resources :pages, only: :tos do
      collection do
        get :tos
        get :tos_edit
        put :tos_update
      end
    end
    namespace :social do
      resource :vk, only: %w(edit update)
      resource :fb, only: %w(edit update)
      resource :tw, only: %w(edit update)
      resource :in, only: %w(edit update)
      resource :ok, only: %w(edit update)
      resource :sms, only: %w(edit update)
      resource :guest, only: %w(edit update)
    end
    post '/events/by_date', to: 'events#by_date', as: 'events_by_date'
  end

  constraints OauthSubdomain do
    resource :widget, only: :show

    namespace :sms do
      get 'authorize', to: 'auth#index'
      post 'auth/send_sms'
      match 'auth/validate', via: %w(get post)
    end

    post '/password', to: 'visitors#auth_by_password'
    get '/:provider/subscribe', to: 'events#subscribe', as: 'event_subscribe'
    match '/:provider/post', to: 'events#post', as: 'event_post', via: [:get, :post]
    get '/:provider/auth', to: 'events#auth', as: 'event_auth'
    get '/:provider/is_member', to: 'events#is_member', as: 'event_member'
    get '/:provider/callback', to: 'sessions#create'
    get '/:provider/setup', to: 'sessions#setup'
    get '/failure', to: 'sessions#failure'
    get '/', to: 'visitors#index', as: :auth
  end
end

app/models/company.rb
class Company < ApplicationRecord
  mount_uploader :cover, CoverUploader
  mount_uploader :card,  CardUploader

  has_secure_token

  has_many :users, dependent: :destroy
  has_many :admins, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :statistics, dependent: :destroy
  has_many :routers, dependent: :destroy
  has_many :devices, dependent: :destroy
  has_one :network, dependent: :destroy
  has_one :vk, dependent: :destroy
  has_one :fb, dependent: :destroy
  has_one :tw, dependent: :destroy
  has_one :in, dependent: :destroy
  has_one :ok, dependent: :destroy
  has_one :sms, dependent: :destroy
  has_one :guest, dependent: :destroy

  validates :name, :owner_name, :phone, :address, presence: true

  def sms
    super || ensure_sms_settings
  end

  def guest
    super || ensure_guest_settings
  end

  private

  def ensure_sms_settings
    create_sms(
      action: 'disabled',
      link_redirect: Figaro.env.link_redirect,
      wall_head: 'StartWifi',
      wall_image: Rails.root.join('app/assets/images/startwifi.png').open
    )
  end

  def ensure_guest_settings
    create_guest(
      action: 'disabled',
      link_redirect: Figaro.env.link_redirect,
      wall_head: 'StartWifi',
      wall_image: Rails.root.join('app/assets/images/startwifi.png').open
    )
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_admin!
  load_and_authorize_resource

  layout 'visitors', only: :suspended

  def index
  end

  def show
    @admins = @company.admins
    @recent_events = @company.events.order('created_at DESC').first(10)
  end

  def new
  end

  def edit
  end

  def create
    @company.cover = Rails.root.join('app/assets/images/startwifi.png').open
    if @company.save
      DummySocialService.new(@company, :fb, :vk, :tw, :in, :ok).call
      redirect_to companies_path, notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @company.update(company_params)
      redirect_to @company, notice: t('.success')
    else
      flash.now[:alert] = t('.errors')
      render :edit
    end
  end

  def destroy
    if @company.destroy
      redirect_to companies_path, notice: t('.success')
    else
      redirect_to @company, alert: t('.errors')
    end
  end

  def hold
    toggle_status = CompanySuspendService.new(@company)
    if toggle_status.call
      redirect_to companies_path, notice: t('.success')
    else
      redirect_to companies_path, alert: t('.errors')
    end
  end

  def suspended
    flash.now[:error] = "Обслуживание приостановлено"
  end

  private

  def company_params
    params.require(:company).permit(:name, :owner_name, :phone, :address, :locale)
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def company_status(company)
    if company.active?
      content_tag :span, '', class: 'active glyphicon glyphicon-ok-circle'
    else
      content_tag :span, '', class: 'hold glyphicon glyphicon-ban-circle'
    end
  end
end

app/views/companies/_form.html.haml
- if @company.errors.any?
  #error_explanation
    %h2
      Form contains
      = pluralize(@company.errors.count, 'error')
    %ul
      - @company.errors.full_messages.each do |error|
        %li= error
= form_for @company do |f|
  .form-group
    = f.label :name, t('.name')
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :owner_name, t('.owner_name')
    = f.text_field :owner_name, class: 'form-control'
  .form-group
    = f.label :phone, t('.phone')
    = f.text_field :phone, class: 'form-control'
  .form-group
    = f.label :address, t('.address')
    = f.text_field :address, class: 'form-control'
  .form-group
    = f.label :locale, t('.locale')
    = f.select :locale, [[t('.locale_russian'), 'ru'], [t('.locale_english'), 'en'], [t('.locale_czech'), 'cz']], {}, class: 'form-control'
  .form-group
    = f.submit t('.save'), class: 'btn btn-primary'

app/views/companies/edit.html.haml
%h2= t('.edit_company')

.row
  .col-md-offset-4.col-md-4
    = render 'form'
    %p= link_to t('.back'), companies_path

app/views/companies/index.html.haml
%h2= t('.all_companies')

- if @companies
  .row
    .col-md-offset-2.col-md-8
      .table-responsive
        %table.table.table-striped
          %thead
            %th= t('.name')
            %th= t('.token')
            %th.text-center= t('.status')
            %th.text-center= t('.options')
          - @companies.each do |company|
            %tr
              %td= link_to company.name, company
              %td= company.token
              %td.text-center
                = link_to hold_company_path(company), method: :put do
                  = company_status(company)
              %td.text-center
                = link_to company_path(company), title: t('.show') do
                  %span.glyphicon.glyphicon-cog
                = link_to edit_company_path(company), title: t('.edit') do
                  %span.glyphicon.glyphicon-pencil
                = link_to company_path(company), title: t('.delete'), method: :delete,
                                                data: { confirm: "#{t('.sure')}" } do
                  %span.glyphicon.glyphicon-trash
      %p= link_to t('.add_new'), new_company_path, class: 'btn btn-primary'

app/views/companies/new.html.haml
%h2= t('.add_company')

.row
  .col-md-offset-4.col-md-4
    - if @company.errors.any?
      #error_explanation
        %h2= "Form contains #{pluralize(@company.errors.count, 'error')}:"
        %ul
          - @company.errors.full_messages.each do |error|
            %li= error
    = form_for @company do |f|
      .form-group
        = f.label :name, t('.name')
        = f.text_field :name, class: 'form-control'
      .form-group
        = f.label :owner_name, t('.owner_name')
        = f.text_field :owner_name, class: 'form-control'
      .form-group
        = f.label :phone, t('.phone')
        = f.text_field :phone, class: 'form-control'
      .form-group
        = f.label :address, t('.address')
        = f.text_field :address, class: 'form-control'
      .form-group
        = f.submit class: 'btn btn-primary'
    %p= link_to t('.back'), companies_path

app/views/companies/show.html.haml
%h2= t('.company', name: @company.name)

.row
  .col-md-6
    %h3= t('.details')
    %table.table.table-striped
      %thead
        %th= t('.attribute')
        %th= t('.description')
      %tbody
        %tr
          %th= t('.name')
          %td= @company.name
        %tr
          %th= t('.contact')
          %td= @company.owner_name
        %tr
          %th= t('.phone')
          %td= @company.phone
        %tr
          %th= t('.address')
          %td= @company.address
        %tr
          %th= t('.token')
          %td= @company.token
        %tr
          %th= t('.options')
          %td
            = link_to t('.edit'), edit_company_path(@company)
            = link_to company_path(@company), method: :delete,
                                             data: { confirm: t('.sure') } do
              = t('.delete')
  .col-md-6
    %h3= t('.admins')
    %table.table.table-striped
      %thead
        %th= t('.email')
        %th= t('.last_signin')
      %tbody
        - @admins.each do |admin|
          %tr
            %td= admin.email
            %td= admin.last_sign_in_at
    %p= link_to t('.add_new'), new_company_admin_path(@company), class: 'btn btn-primary'
.row
  .col-md-6
    %h3= t('.last_events')
    %table.table.table-striped
      %thead
        %th
        %th= t('dashboards.show.time')
        %th= t('dashboards.show.action')
        %th= t('dashboards.show.link')
      %tbody
        - @company.events.last25.each do |event|
          %tr
            %th= fa_icon icon_class_by event.user.provider
            %td= event.created_at
            %td= humanize_event(event.action)
            %td= link_to event.user.name, user_path(event.user)